[package]
name = "my_game"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.0"

[lints.clippy]
type-complexity = "allow"
too-many-arguments = "allow"
double-parens = "allow"

[lints.rust]
unused_parens = "allow"
